### PR TITLE
Feature/suport db metadata

### PR DESCRIPTION
**Pull request by yuxabc**
@songb @philfriesen please review, merge and delete.

### CODE REVIEW

**Comment by yuxabc** [comment]
https://github.com/advisory/greendale/pull/1020

**Comment by yuxabc** [comment]
https://github.com/advisory/eab_base/pull/440

**Comment by philfriesen** [comment]
@songb I'm done reviewing. Please merge and delete.

**Comment by Muizudeen** [comment]
@songb @philfriesen hope you guys are doing okay. I'm still receiving these notifications. I'm not sure you unsubscribed me correctly when I last notified you. Kindly address. Cheers

**Comment by philfriesen** [comment]
@Muizudeen We hope you are doing well also. Can you remove yourself as a watcher from this repository? I have no way of doing this centrally. See http://stackoverflow.com/questions/11497476/github-remove-watchers-of-a-repository .

**Pull request merged**
