### PR TITLE
Removed custom tenant config loader.

### PR DESCRIPTION
**Pull request by jprashanth**
Projects using this django app can simply specify their own loader
using the settings SAML_CONF_LOADER.

When the changes are reviewed and accepted

- [ ] Update CHANGES file
- [ ] Update setup.py to bump the version
- [ ] Create a new tag/release
- [ ] Upload to `pypi`

### CODE REVIEW

**Comment by yuxabc** [comment]
Whenever making changes to djangosaml2_tenant, please make sure to publish the new version to PyPI so that our apps are able to install it.

**Comment by jprashanth** [comment]
@philfriesen @yuxabc Please review the changes. If the changes are acceptable, I will go ahead with the further changes needed.

**Comment by philfriesen** [comment]
@jprashanth I'll have to trust you on these changes, because I can't really follow/understand them without seeing tests change.
@yuxabc Please review.

**Comment by jprashanth** [comment]
@philfriesen I understand.

@philfriesen @yuxabc For a better context, I have ripped out most of the code, that **WE** wrote as part of this fork, and put it in to `eab_base`.

**Comment by yuxabc** [comment]
@jprashanth It looks good. I merged the PR and please proceed steps in your checklist. Thanks!

**Comment by kingbuzzman** [comment]
👍  i like when there is more deletions than additions, less code == happy times

**Pull request merged**
